# markdown: kramdown
# kramdown:
#   input: GFM
#   auto_ids: false

markdown: Redcarpet
Redcarpet:
    extensions: ["fenced_code_blocks", "no_intra_emphasis", "autolink", "strikethrough", "with_toc_data", "space_after_headers","prettify"]

permalink: /:title
