# 站点设置
title:              myzerone
bio:                '嗨，大家好，我是一位来自中国的iOS开发者'
description:        "记录下自己学习的过程、点滴，也为了分享自己的收获。"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             zh_CN

# 服务器选项
detach:  false
port:    4000
host:    127.0.0.1
baseurl: ""
#baseurl: "http://myzerone.com" # does not include hostname

# 目录结构
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data
# collections: null
sass:
  sass_dir:         _sass
  style:            compressed

# 阅读处理
safe:         false
include:      [".htaccess"]
exclude:      [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 内容过滤
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# 插件
whitelist: []
gems:      []

# 转换
markdown:           kramdown
highlighter:        rouge
mathjax:            false
lsi:                false
excerpt_separator:  "\n\n"
incremental:        false

# 输出
permalink:     /:title/
paginate_path: /page:num
timezone:      null

quiet:    false
defaults: []

# Markdown 处理器
rdiscount:
  extensions: []

redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
    - with_toc_data
    - space_after_headers
    - prettify
    - tables
    - superscript
# redcarpet :
#   extensions : ["fenced_code_blocks", "no_intra_emphasis", "autolink", "strikethrough", "with_toc_data", "space_after_headers","prettify", "tables", "superscript"]

kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# 评论
commentFlag:        true
#disqus_shortname:   taylantatli
commentitUsername:  myzerone
commentitRepo:      myzerone/myzerone.github.io

#社会化组建
#if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              myzerone@myzerone.com
#twitter:            username
#facebook:           username
github:             xj01
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
jekyll-mentions:
    base_url: https://github.com
