# 站点设置
title:              myzerone
bio:                '嗨，大家好，我是一位来自中国的iOS开发者'
description:        "记录下自己学习的过程、点滴，也为了分享自己的收获。"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             zh_CN

# 服务器选项
detach:  false
port:    4000
host:    127.0.0.1
# url:     "https://myzerone.com"
# url:     "http://127.0.0.1:4000"
baseurl: ""

# 目录结构
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir:    ./_data
collections:
    notes:
        output: true
        permalink: /notes/:year/:month/:day/:title/
    projects:
        output: true
        permalink: /projects/:year/:month/:day/:title/
sass:
  sass_dir:         _sass
  style:            compressed

# 头信息默认值设置
defaults:
  -
    scope:
      path: ""
      type: projects # 项目布局属性设置
    values:
      layout: project
  -
    scope:
      path: ""
      type: notes     # 随笔布局属性设置
    values:
      layout: note


# 阅读处理
safe:         false
include:      [".htaccess"]
# 忽略文件／文件夹配置，_config.yml和以“.”开头的文件／文件夹自动忽略。
exclude:      [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 内容过滤
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# 插件
whitelist: []
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
jekyll-mentions:
    base_url: https://github.com

# 转换
markdown:           kramdown
highlighter:        rouge
mathjax:            false
lsi:                false
excerpt_separator:  "\n\n"
incremental:        false

# 输出
permalink:     /posts/:year/:month/:day/:title/
paginate_path: /page:num
timezone:      null

quiet:    false

# Markdown 处理器
kramdown:
  input:          GFM
  auto_ids:       true
  auto_id_prefix: 'id-'
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # enable_coderay: true
  # coderay:
  #   coderay_wrap:              div
  #   coderay_line_numbers:      inline
  #   coderay_line_number_start: 1
  #   coderay_tab_width:         2
  #   coderay_bold_every:        10
  #   coderay_css:               style

# 评论
commentFlag:        true
commentitUsername:  myzerone
commentitRepo:      myzerone/myzerone.github.io

#社会化组建
#if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-83690324-2
  verify:           Oq-I-tGK8y1zoHLnZQnfe7rH6rkjqyjqZfBtvADe2uU
  #ad-client:
  #ad-slot:
#bing-verify:
email:              myzerone@outlook.com
#twitter:            username
#facebook:           username
github:             myzerone
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
